import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#ffffff' },
  title: { fontSize: 22, fontWeight: '700', textAlign: 'center', marginTop: 12, marginBottom: 20, color: '#111827' },
  avatarWrapper: { alignItems: 'center' },
  avatar: { width: 100, height: 100, borderRadius: 50 },
  avatarPlaceholder: { backgroundColor: '#e5e7eb', justifyContent: 'center', alignItems: 'center' },
  avatarInitial: { fontSize: 36, fontWeight: '600', color: '#6b7280' },
  name: { fontSize: 20, fontWeight: '700', textAlign: 'center', marginTop: 14, color: '#111827' },
  email: { fontSize: 14, color: '#6b7280', textAlign: 'center', marginTop: 4 },
  statsCard: { flexDirection: 'row', backgroundColor: '#f3f4f6', borderRadius: 16, marginHorizontal: 20, marginTop: 20, paddingVertical: 16 },
  statItem: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  divider: { width: 1, backgroundColor: '#d1d5db' },
  statValue: { fontSize: 16, fontWeight: '700', color: '#111827' },
  statValueText: { fontSize: 14, fontWeight: '700', color: '#111827' },
  statLabel: { fontSize: 12, color: '#9ca3af', marginTop: 4 },
  toggleRow: { flexDirection: 'row', marginHorizontal: 20, marginTop: 20, gap: 12 },
  toggleButton: { flex: 1, backgroundColor: '#111827', borderRadius: 24, paddingVertical: 12, alignItems: 'center', justifyContent: 'center' },
  toggleButtonOutline: { backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#d1d5db' },
  toggleButtonActive: {},
  toggleText: { color: '#ffffff', fontWeight: '600', fontSize: 14 },
  toggleTextOutline: { color: '#111827' },
  toggleTextActive: {},
  separator: { height: 1, backgroundColor: '#e5e7eb', marginTop: 20 },
  listContent: { flexGrow: 1 },
  inviteRow: { paddingHorizontal: 20, paddingVertical: 12 },
  emptyState: { alignItems: 'center', justifyContent: 'center', paddingVertical: 80 },
  emptyText: { color: '#9ca3af', fontSize: 15 },
});
